title: Gourab Bagchi # your name (or website title) here
logo: "/images/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Hi, I am an AI Architect with over 9 years of combined professional experience across industry roles and advance postgraduate education in computer vision, natural language processing (LLMs), multimodal AI, and data science. Proficient in Python, R, and related tools, I specialize in predictive modeling and deriving actionable insights from complex datasets to drive informed decision-making.
  <br><br>
  <a href="https://www.linkedin.com/in/gourab-bagchi-610788135/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-6GNFW3VBX4 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
