title: Gourab Bagchi # your name (or website title) here
logo: "/images/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Hi, I am a seasoned Machine Learning Engineer and Data Science Researcher. I specialize in analytics, natural language processing, and machine learning, with over 5 years of professional experience. Proficient in utilizing Python, R, and relevant tools, I conduct advanced predictive modeling and uncover insightful trends, patterns, and correlations within datasets, enabling data-driven decision-making processes.
  <br><br>
  <a href="https://www.linkedin.com/in/gourab-bagchi-610788135/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-6GNFW3VBX4 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
